"""Collect a scope-sample bundle from a capture root.

Walks a smart-telescope capture root and emits a single text file containing:
  - a directory tree (names only, no absolute paths)
  - primary FITS header values for up to N files per leaf directory

The output contains no pixel data and no full filesystem paths. Share it on
a GitHub issue when requesting a new scope adapter.

Usage:
    uv run scripts/collect_scope_sample.py /path/to/captures

    # with options
    uv run scripts/collect_scope_sample.py /path/to/captures \\
        --scope-name SEESTAR_S50 \\
        --fits-per-dir 2 \\
        --max-depth 5 \\
        --no-redact          # keep RA/DEC/DATE-OBS (not recommended)
        --redact-object      # also mask OBJECT (target name)
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

# Pull the canonical header list from fits_reader so it stays in sync
# automatically when new keys are added there.
_repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_repo_root))

from server.catalog.fits_reader import HEADER_KEYS_TO_KEEP  # noqa: E402

try:
    from astropy.io import fits as _fits
except ImportError:
    print(
        "astropy is not installed. Run `uv sync` from the repo root first.",
        file=sys.stderr,
    )
    sys.exit(1)

_SKIP_DIRS = {".git", "node_modules", "__pycache__"}
_REDACT_ALWAYS = {"RA", "DEC", "DATE-OBS"}
_REDACT_OBJECT = {"OBJECT"}

BANNER = """\
astrolab scope sample
=====================
Generated by scripts/collect_scope_sample.py.
This file contains directory structure and FITS primary header values only.
No pixel data is included. RA, DEC, and DATE-OBS are redacted by default.

Attach this file to a GitHub issue at https://github.com/bscholer/astrolab/issues
when requesting a new scope adapter.
"""


def _read_header(path: Path, redact: bool, redact_object: bool) -> dict[str, object]:
    out: dict[str, object] = {}
    try:
        header = _fits.getheader(path, ext=0)
        for key in HEADER_KEYS_TO_KEEP:
            if key not in header:
                continue
            val = header[key]
            if isinstance(val, str):
                val = val.strip()
            if redact and key in _REDACT_ALWAYS:
                val = "REDACTED"
            if redact_object and key in _REDACT_OBJECT:
                val = "REDACTED"
            out[key] = val
    except Exception as exc:  # noqa: BLE001
        out["_error"] = str(exc)
    return out


def _walk(
    root: Path,
    rel: Path,
    depth: int,
    max_depth: int,
    max_files_per_dir: int,
    fits_per_dir: int,
    redact: bool,
    redact_object: bool,
    lines: list[str],
    indent: str = "",
) -> None:
    if depth > max_depth:
        lines.append(f"{indent}[max depth reached]")
        return

    try:
        entries = sorted(root.iterdir())
    except PermissionError:
        lines.append(f"{indent}[permission denied]")
        return

    dirs = [e for e in entries if e.is_dir() and e.name not in _SKIP_DIRS]
    files = [e for e in entries if e.is_file()]

    shown_files = files[:max_files_per_dir]
    omitted = len(files) - len(shown_files)

    fits_shown = 0
    for f in shown_files:
        lines.append(f"{indent}{f.name}")
        if f.suffix.lower() == ".fits" and fits_shown < fits_per_dir:
            fits_shown += 1
            hdr = _read_header(f, redact=redact, redact_object=redact_object)
            if hdr:
                lines.append(f"{indent}  headers:")
                for k, v in hdr.items():
                    lines.append(f"{indent}    {k}: {v!r}")

    if omitted:
        lines.append(f"{indent}... ({omitted} more file(s) not shown)")

    for d in dirs:
        lines.append(f"{indent}{d.name}/")
        _walk(
            d,
            rel / d.name,
            depth + 1,
            max_depth,
            max_files_per_dir,
            fits_per_dir,
            redact,
            redact_object,
            lines,
            indent + "  ",
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("root", type=Path, help="Capture root to scan.")
    parser.add_argument(
        "--scope-name",
        default="UNKNOWN",
        metavar="NAME",
        help="Label for the bundle (e.g. SEESTAR_S50). Used in the output filename.",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=4,
        metavar="N",
        help="How deep to descend into subdirectories. Default: 4.",
    )
    parser.add_argument(
        "--max-files-per-dir",
        type=int,
        default=5,
        metavar="N",
        help="Max filenames to list per directory. Default: 5.",
    )
    parser.add_argument(
        "--fits-per-dir",
        type=int,
        default=1,
        metavar="N",
        help="Number of FITS files per directory to read headers from. Default: 1.",
    )
    parser.add_argument(
        "--no-redact",
        dest="redact",
        action="store_false",
        default=True,
        help="Keep RA, DEC, and DATE-OBS in the output. Not recommended.",
    )
    parser.add_argument(
        "--redact-object",
        action="store_true",
        default=False,
        help="Also mask the OBJECT header (target name). Use if your target names reveal location.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        metavar="FILE",
        help="Output file path. Default: astrolab-scope-sample-<scope>-<date>.txt in cwd.",
    )
    args = parser.parse_args()

    root: Path = args.root.resolve()
    if not root.exists():
        print(f"error: {root} does not exist", file=sys.stderr)
        sys.exit(1)
    if not root.is_dir():
        print(f"error: {root} is not a directory", file=sys.stderr)
        sys.exit(1)

    today = datetime.date.today().isoformat()
    scope_tag = args.scope_name.upper().replace(" ", "_")
    out_path: Path = args.output or Path(f"astrolab-scope-sample-{scope_tag}-{today}.txt")

    lines: list[str] = []
    lines.append(BANNER)
    lines.append(f"scope:   {args.scope_name}")
    lines.append(f"date:    {today}")
    redact_ra = "yes" if args.redact else "no"
    redact_obj = "yes" if args.redact_object else "no"
    lines.append(f"redact:  RA/DEC/DATE-OBS={redact_ra}  OBJECT={redact_obj}")
    lines.append("root:    <capture root>")
    lines.append("")
    lines.append("Directory tree")
    lines.append("-" * 60)
    lines.append("<capture root>/")

    _walk(
        root,
        Path("."),
        depth=1,
        max_depth=args.max_depth,
        max_files_per_dir=args.max_files_per_dir,
        fits_per_dir=args.fits_per_dir,
        redact=args.redact,
        redact_object=args.redact_object,
        lines=lines,
        indent="  ",
    )

    lines.append("")
    lines.append("FITS header keys checked")
    lines.append("-" * 60)
    for k in HEADER_KEYS_TO_KEEP:
        redacted_note = ""
        if args.redact and k in _REDACT_ALWAYS:
            redacted_note = "  [redacted]"
        if args.redact_object and k in _REDACT_OBJECT:
            redacted_note = "  [redacted]"
        lines.append(f"  {k}{redacted_note}")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out_path}")
    print("open it in a text editor to review before posting to GitHub.")


if __name__ == "__main__":
    main()
